cudatoolkit:
  - 11.2
  - 11.3
  - 11.4
c_compiler_version:    # [linux or win]
  - 9.3                # [linux or win]
cxx_compiler_version:  # [linux or win]
  - 9.3                # [linux or win]
