package:
  name: libastra
  version: '2.0.0'

source:
  git_url: https://github.com/astra-toolbox/astra-toolbox.git
  git_tag: master

build:
  number: 0
  string: cuda_{{ cudatoolkit }}_0 # [linux]

requirements:
  build:
    - {{ compiler('c') }}    # [win or linux]
    - {{ compiler('cxx') }}  # [linux]
    - boost # [osx]
    - automake # [osx]
    - autoconf # [osx]
    - libtool # [osx]
  host:
    - boost # [osx or linux]
    - cudatoolkit {{ cudatoolkit }} # [linux]
    # libstdcxx-ng 9.3 introduces extra host system requirements on glibc
    # For the older systems (debian8, debian9) we use g++ 5.4 and 7.3, resp.
    {% if linux and cxx_compiler_version in ['5.4', '7.3'] -%}
    - libstdcxx-ng <9.3 # [linux]
    {% endif %}
  run:
    # See: https://github.com/conda-forge/conda-forge.github.io/issues/687#issuecomment-460095230
    - {{ pin_compatible('cudatoolkit', max_pin='x.x') }} # [linux]

about:
  home: http://www.astra-toolbox.com
  license: GPLv3
  summary: 'The ASTRA Toolbox is a Python toolbox of high-performance GPU primitives for 2D and 3D tomography.'
